use_frameworks!

platform :ios, '12.0'

target 'Tg3dSDK-iOS_Example' do
  pod 'Tg3dMobileScanSDK-iOS', :path => '../'
  pod 'I3DRecorder', :git => 'https://github.com/TG3Ds/in3D-iOS-SDK.git'
  pod 'ZIPFoundation', '~> 0.9'
  target 'Tg3dSDK-iOS_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 9.0.0'
  end
end
